gpak-1.txt → gpak-1

diff --git a/xpak2gpkg b/xpak2gpkg
--- a/xpak2gpkg
+++ b/xpak2gpkg
@@ -52,7 +52,7 @@ esac
 
 basename=${filename%.xpak}
 mkdir "${basename}" || die "mkdir failed"
-touch "${basename}/gpkg-1.txt" || die "touch gpkg-1.txt failed"
+touch "${basename}/gpkg-1" || die "touch gpkg-1 failed"
 
 echo "Repacking metadata ..." >&2
 mkdir "${basename}/metadata" || die "mkdir metadata failed"
@@ -80,7 +80,7 @@ gpg --detach-sign "${basename}/image.tar${comp_suffix}" || die "signing image fa
 echo "Packing the final tarball ..." >&2
 cd - >/dev/null || die "cd back failed"
 tar --format=gnu -c -b 1 -C "${tmpdir}" -f "${output}" \
-	"${basename}/gpkg-1.txt" \
+	"${basename}/gpkg-1" \
 	"${basename}/metadata.tar${comp_suffix}.sig" \
 	"${basename}/metadata.tar${comp_suffix}" \
 	"${basename}/image.tar${comp_suffix}.sig" \
